name: cron

on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 5 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🍳 Update README
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        run: |
          cd ${GITHUB_WORKSPACE}/src/
          pip install feedparser
          python main.py
      - name: 🚀 Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "feat(auto generate): Updated content"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
